### ISSUE TITLE
Question: Invalid hooks call when using createElement from emotion

### ISSUE THREAD

**Issue by sigma-andex** [collegevine/purescript-elmish#36]
Hi there,

I'm trying to adapt [react-basic-emotion](https://github.com/lumihq/purescript-react-basic-emotion) to elmish instead, but I can't get it running. Basically I adapted the [js code](https://github.com/sigma-andex/purescript-react-basic-emotion/blob/switch-to-elmish/src/React/Basic/Emotion.js#L21-L29) and tried to get that running using the types from elmish, see [here](https://github.com/sigma-andex/purescript-react-basic-emotion/blob/switch-to-elmish/src/React/Basic/Emotion.purs#L151-L171). But I get the following error:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

I checked according to the documentation and am pretty certain that I don't have mismatching versions or more than one copy of react.

From what I can see, the `createElement` code in react-basic-emotion looks pretty similar to the `createElement` in elmish. Do you have any idea what I could be missing?

**Comment by fsoikin** [comment]
Hi @sigma-andex!

Would you mind showing the Elmish-targeted code that's failing for you?

It's a bit hard to tell what's wrong with your approach without seeing your approach :-)

**Comment by sigma-andex** [comment]
Sure. I uploaded a minimal project: https://github.com/sigma-andex/elmish-emotion-test/
with the code here: https://github.com/sigma-andex/elmish-emotion-test/blob/main/src/Main.purs

**Comment by fsoikin** [comment]
Sorry, I meant the code of the library, not the app.
I see your project is using a dependency named `elmish-emotion`. Where can I look at it?

**Comment by sigma-andex** [comment]
It's a fork of purescript-react-basic-emotion, the code is on branch `swtich-to-elmish`: 
https://github.com/sigma-andex/purescript-react-basic-emotion/tree/switch-to-elmish

**Comment by fsoikin** [comment]
I don't yet have time to compile, run, and debug, but the first thing that jumps to mind is that your `createElement_` implementation in the foreign module doesn't match its type signature in the PS code:

```
// JS
exports.createElement_ = (component, props, areChildrenDynamic) => 

-- PS
foreign import createElement_ :: forall props. Fn3 (ReactComponent props) props (Array ReactElement) ReactElement
```

The JS implementation expects the third parameter to be a boolean, and then expects to find actual children passed as `props.children`, whereas PS code is passing the children array as third parameter and _not_ including it in `props`.

**Comment by fsoikin** [comment]
Separately, might I suggest a more flexible approach?

Instead of implementing the `div` function on your own (and then, presumably, reimplementing all the other tags?), why not have your library simply produce values of type `Elmish.HTML.CSS`? Then such values could be trivially used with existing `Elmish.HTML` combinators, e.g.:

```
import Elmish.HTML as H
import Elmish.Emotion as E

myDiv = H.div { css: E.css { size: E.px 50 } }
```

**Comment by sigma-andex** [comment]
> I don't yet have time to compile, run, and debug, but the first thing that jumps out is that your `createElement_` implementation in the foreign module doesn't match its type signature in the PS code:
> 
> ```
> // JS
> exports.createElement_ = (component, props, areChildrenDynamic) => 
> 
> -- PS
> foreign import createElement_ :: forall props. Fn3 (ReactComponent props) props (Array ReactElement) ReactElement
> ```
> 
> The JS implementation expects the third parameter to be a boolean, and then expects to find actual children passed as `props.children`, whereas PS code is passing the children array as third parameter and _not_ including it in `props`.

Right. I have changed that now to this: 
```purescript
exports.createElement_ = (component, props, children) => {
  const args = [component, flattenDataProp(component, props)];
  return createElement.apply(
    null,
    children
  );
```
but that doesn't seem to be the problem.



> Separately, might I suggest a more flexible approach?
> 
> Instead of implementing the `div` function on your own (and then, presumably, reimplementing all the other tags?), why not have your library simply produce values of type `Elmish.HTML.CSS`? Then such values could be trivially used with existing `Elmish.HTML` combinators, e.g.:
> 
> ```
> import Elmish.HTML as H
> import Elmish.Emotion as E
> 
> myDiv = H.div { css: E.css { size: E.px 50 } }
> ```

Yes my idea would be to adapt your html tag generator code to create the new tags. 


So the difference is, as far as I understand it, that in elmish-html a style is created for each tag. so if the style gets quite big, it is added to each tag. While in emotion, a css class is created from the style and then this className is added to the tag. This makes reusing a style much more efficient.

**Comment by fsoikin** [comment]
Also, just out of curiosity, why are you reimplementing `createElement` instead of using [the one from `Elmish` itself](https://github.com/collegevine/purescript-elmish/blob/master/src/Elmish/React.js#L12)? As far as I can see, it's doing the exact same thing.

**Comment by fsoikin** [comment]
> So this one is not using the React.createElement, but the Emotion.createElement:

As far as I understand, that's not necessary as long as you convert the CSS record to a class name via `Emotion.css`

**Comment by fsoikin** [comment]
Actually, now that I think about it, why not just return a `String` and simply plug into `className`?

This would work with both `Elmish.HTML`:

```
import Elmish.HTML as H
import Elmish.Emotion as E

myDiv = H.div { className: E.css { ... } } "foo"
```

And with `Elmish.HTML.Styled`:

```
import Elmish.HTML.Styled as H
import Elmish.Emotion as E

myDiv = H.div (E.css { ... }) "foo"
```

**Comment by sigma-andex** [comment]
Ok I just tried that, but that is not how it works. Got the following error:
```
You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop).
```

**Comment by sigma-andex** [comment]
So the difference between emotion and elmish-html is this:

Emotion:
<img width="359" alt="Screenshot 2021-04-29 at 20 48 29" src="https://user-images.githubusercontent.com/77549848/116612303-4c160280-a92f-11eb-8246-8455082c948d.png">

Elmish-html
<img width="672" alt="Screenshot 2021-04-29 at 21 00 25" src="https://user-images.githubusercontent.com/77549848/116612297-4b7d6c00-a92f-11eb-8423-291ce3f325f1.png">

**Comment by sigma-andex** [comment]
So I think its creating the style classes within an react component, thats why it needs to use the createElement

**Comment by fsoikin** [comment]
Take a look at the very first example at https://emotion.sh.

**Comment by sigma-andex** [comment]
Yes, I tried that, but it doesnt work. So e.g. when I do 
```purescript
helloWorld :: ReactElement
helloWorld =  R.div { className : big } $ R.text "Hello 🗺"
```
it renders the following div:
```
<div class="You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop).">Hello 🗺</div>
```

**Comment by fsoikin** [comment]
That's because you're importing `css` from `@emotion/react`, not from `@emotion/css`.
Again, take a look at the very first example at https://emotion.sh
Or check out this example I just made: https://runkit.com/embed/b5i54cezfovj

**Comment by sigma-andex** [comment]
🤦  geez you are right, I completely oversaw that it's a different package! That indeed works. Thank you very much. 
But a question remains: Doing it that way causes a side-effect (of constructing the class). Wouldn't the element approach encapsulate this?

**Comment by fsoikin** [comment]
Well, looking at their code for `createElement`, that's what Emotion does anyway: it causes a side-effect every time you call `css` and/or `createElement`.
