### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by tbm206** [collegevine/purescript-elmish#75]
Hi,

Excellent library. I'm considering migrating to Elmish from another PS library but was wondering how routing could be implemented? I'm using hash-based routing using [`purescript-routing`](https://github.com/purescript-contrib/purescript-routing)

**Comment by fsoikin** [comment]
Hi @tbm206!

I started writing a response and scrapped it several times, until I finally realized that the reason I'm having difficulty with it is that I don't know the question I'm trying to answer.

Could you please clarify what specifically is the difficulty you're having when trying to use Elmish with a routing library?

**Comment by tbm206** [comment]
> Hi @tbm206!
> 
> I started writing a response and scrapped it several times, until I finally realized that the reason I'm having difficulty with it is that I don't know the question I'm trying to answer.
> 
> Could you please clarify what specifically is the difficulty you're having when trying to use Elmish with a routing library?

Apologies if the question wasn't clear.

In Elm, there is the `Browser.Navigation` module that can be plugged into the state of the app. The `Navigation` module will _fire actions_ in response to URL changes. There is also the need to change the URL but I guess this is easier using `Transition`. So, basically, the question is about synching the URL state with the app in both directions.

**Comment by fsoikin** [comment]
I see. What you're looking for is what in Elm is called "subscriptions" - a way to spawn a parallel process that can listen to something and occasionally shoot messages to the UI.

Elm doesn't have "subscriptions" as a thing, but you can achieve the same effect with `forks`. Just spawn it in your `init` function, and have it listen to the browser location and fire events:

```
data Message = ... | UrlChanged String | ...

init :: Args -> Transition Message State
init args = do
  forks \dispatch ->
    Browser.onUrlChanged \newUrl -> dispatch (UrlChanged newUrl)

  .,..
```

**Comment by tbm206** [comment]
Thanks @fsoikin; that's exactly what I'm looking for

**Comment by fsoikin** [comment]
I'm glad I was able to help.
I'm going to close the issue now. 
Let me know if you need more advice.
